services:
  post-service:
    build: .
    ports:
      - "3002:3002"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:password@db:5433/posts
    depends_on:
      - db

  db:
    build: ./db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - jpeg
    restart: always

volumes:
  db_data:

networks:
  jpeg:
    external: true